### ISSUE TITLE
How important do you think it is for your career to write a book?

### ISSUE THREAD

**Issue by cassiemc** [pearlchen/ama#1]

**Comment by pearlchen** [comment]
You and I are both writers (in different ways, of course!) so being an author of a book is probably more important to us than the majority of the general population, or to even those in the tech crowd, but I don't think it's any predictor of future success.

Reasons why **I** would want to have a full book under my belt:
- organize my thoughts into a major thesis
- for a print book, to offer someone an experience that isn't solely screen-based
- to have a feeling of immense satisfaction and accomplishment -- books are hard work!

But having said that, with today's online reading and link sharing habits (e.g. social media sharing, Pocket), I think focussed articles can be **more** effective at reaching a wider and larger audience -- which, imo, is more satisfying than having a book with a small audience.
