### ISSUE TITLE
What does your phone homescreen look like?

### ISSUE THREAD

**Issue by sindresorhus** [pearlchen/ama#3]
Screenshot please. I ask everyone this as it tells a lot about a person. [Mine for example.](https://github.com/sindresorhus/ama/issues/64)

**Comment by pearlchen** [comment]
![screenshot_2015-07-11-21-52-59](https://cloud.githubusercontent.com/assets/408903/8636029/7fd62388-2817-11e5-934e-a3a48add2491.png)

Hmm, what does mine tell you about me?

**Comment by pearlchen** [comment]
Also worth noting, I use Nova Launcher instead of the default HTC/Android launcher.
